server {
  listen       80;
  server_name  localhost;
  # root /usr/share/nginx/html/public;
  # index index.html index.htm;

  location / {
    # autoindex on;
    root /usr/share/nginx/html/studio/public;
    index index.html index.htm;
    try_files $uri $uri/ /studio/index.html =404;
  }

  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
