name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'release/*'

    tags:
      - '*'

  pull_request:
    branches:
      - main
      - develop
      - 'release/*'
      -
env:
  MAIN_REPO: IN-CORE/incore-studio

jobs:

  # ----------------------------------------------------------------------
  # NODE BUILD
  # ----------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - "18"

    steps:
      # checkout source code
      - uses: actions/checkout@v3

      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # configure npm auth for GitHub Packages
      - name: Configure npm auth
        run: |
          echo "@ncsa:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GEO_EXPLORER_GITHUB_TOKEN }}" >> ~/.npmrc

      # install dependencies
      - name: install dependencies
        run: npm install

      # compile UI
      - name: build
        run: npm run build
